baseURL = "https://aibookkeepingtools.com/"
languageCode = "en-us"
title = "AI Bookkeeping Tools"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  showtoc = true
  tocopen = true
  description = "Compare and master AI bookkeeping software, workflows, and tutorials."

[markup.goldmark.renderer]
  unsafe = true

[minify]
  minifyOutput = true

