baseURL = "https://aibookkeepingtools.com/"
title   = "Best AI Bookkeeping Tools 2025 | Automate Your Accounting"
theme   = "PaperMod"
languageCode = "en-us"
googleAnalytics = "G-6TESE2Z3E2"

# Build settings
buildDrafts  = false
buildFuture  = true
publishDir = "public"
buildExpired = false
enableRobotsTXT = true

# Pagination (Hugo 0.128+)
[pagination]
  pagerSize = 10


[params]
  env              = "production"
  description      = "Discover the best AI bookkeeping tools for small businesses in 2025. Compare features, pricing, and automation capabilities for QuickBooks, Xero, and modern AI accounting software."
  keywords         = ["AI bookkeeping tools", "automated accounting software", "QuickBooks AI", "small business bookkeeping", "receipt OCR", "expense tracking apps"]
  author           = "AI Bookkeeping Tools"
  defaultTheme     = "auto"
  disableThemeToggle = false
  mainSections     = ["posts"]
  summaryLength = 25   # number of words Hugo uses for .Summary
  cspNonce = "abc123xyz"

  # UI features
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowReadingTime  = true
  ShowToc          = true
  ShowBreadCrumbs  = true
  comments         = false
  
  # SEO / meta
  disableSpecial1stPost = false
  hideMeta              = false
  showMeta              = true
  
  # Assets
  [params.assets]
    favicon = "/favicon.ico"
    apple_touch_icon = "/apple-touch-icon.png"

  # Homepage SEO
  [params.homeInfoParams]
    Title = "AI-Powered Bookkeeping Solutions for Modern Businesses"
    Content = """
**Streamline your accounting with cutting-edge AI tools.** 

Discover comprehensive guides, reviews, and tutorials on the latest AI bookkeeping software. From automated QuickBooks workflows to intelligent receipt scanning, we help small businesses and accountants leverage artificial intelligence to save time and reduce errors.

**Featured Topics:** AI Expense Tracking • Automated Receipt OCR • QuickBooks Integration • CPA Workflow Optimization
    """

# Menus (match SecureStackOps style)
[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1
  [[menu.main]]
    name   = "Posts"
    url    = "/posts/"
    weight = 2
  [[menu.main]]
    name   = "Tags"
    url    = "/tags/"
    weight = 3
  [[menu.main]]
    name   = "Search"
    url    = "/search/"
    weight = 4

# Taxonomies
[taxonomies]
  tag      = "tags"
  category = "categories"

# Privacy
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true

# Markup
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4


[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Outputs 
[outputs]
  home     = ["HTML", "RSS", "Sitemap", "JSON"]
  section  = ["HTML", "RSS", "Sitemap"]        # Added Sitemap here
  page     = ["HTML", "Sitemap"]           
  taxonomy = ["HTML", "RSS"]
  term     = ["HTML", "RSS"]
