baseURL = "https://aibookkeepingtools.com/"
title   = "AI Bookkeeping Tools"
theme   = "PaperMod"
languageCode = "en-us"

# Build settings
buildDrafts  = false
buildFuture  = true
buildExpired = false
enableRobotsTXT = true

# Pagination (Hugo 0.128+)
[pagination]
  pagerSize = 10

# Outputs (add JSON so PaperMod search works)
[outputs]
  home     = ["HTML", "RSS", "Sitemap", "JSON"]
  section  = ["HTML", "RSS"]
  page     = ["HTML"]
  taxonomy = ["HTML", "RSS"]
  term     = ["HTML", "RSS"]

[params]
  env              = "production"
  description      = "Guides, reviews, and tutorials on AI bookkeeping tools, QuickBooks automations, and receipt OCR."
  author           = "AI Bookkeeping Tools"
  defaultTheme     = "auto"
  disableThemeToggle = false
  mainSections     = ["posts"]
  summaryLength = 25   # number of words Hugo uses for .Summary
  cspNonce = "abc123xyz"

  # UI features
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowReadingTime  = true
  ShowToc          = true
  ShowBreadCrumbs  = true
  comments         = false

  # SEO / meta
  disableSpecial1stPost = false
  hideMeta              = false
  showMeta              = true

  # Assets
  [params.assets]
    favicon = "/favicon.ico"
    apple_touch_icon = "/apple-touch-icon.png"

# Menus (match SecureStackOps style)
[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1

  [[menu.main]]
    name   = "Posts"
    url    = "/posts/"
    weight = 2

  [[menu.main]]
    name   = "Tags"
    url    = "/tags/"
    weight = 3

  [[menu.main]]
    name   = "Search"
    url    = "/search/"
    weight = 4

# Taxonomies
[taxonomies]
  tag      = "tags"
  category = "categories"

# Privacy
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true

# Markup
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4

[sitemap]
  changefreq = "weekly"
  priority = 0.5

mediaTypes:
  application/xml:
    suffixes: ["xml"]

