baseURL = "https://aibookkeepingtools.com/"
title   = "AI Bookkeeping Tools"
theme   = "PaperMod"
languageCode = "en-us"

# Build settings
buildDrafts  = false
buildFuture  = true
buildExpired = false
enableRobotsTXT = true

# Hugo 0.128+ pagination key (replaces deprecated 'paginate')
[pagination]
  pagerSize = 10

# Ensure all kinds are emitted (incl. full sitemap)
[outputs]
  home    = ["HTML", "RSS", "Sitemap"]
  section = ["HTML", "RSS"]
  page    = ["HTML"]
  taxonomy = ["HTML", "RSS"]
  term     = ["HTML", "RSS"]

# Sitemap settings (use Hugo’s built-in generator)
[sitemap]
  changefreq = "weekly"
  priority   = 0.5
  filename   = "sitemap.xml"

[params]
  env              = "production"
  description      = "Guides, reviews, and tutorials on AI bookkeeping tools, QuickBooks automations, and receipt OCR."
  author           = "AI Bookkeeping Tools"
  defaultTheme     = "auto"
  mainSections     = ["posts"]

  # UI features
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowReadingTime  = true
  ShowToc          = true
  ShowBreadCrumbs  = true
  comments         = false

  # SEO / meta
  disableSpecial1stPost = false
  hideMeta              = false
  showMeta              = true

  # Assets
  [params.assets]
    favicon = "/favicon.ico"
    apple_touch_icon = "/apple-touch-icon.png"

# Menus
[menu]
  [[menu.main]]
    name  = "Posts"
    url   = "/posts/"
    weight = 10

  [[menu.main]]
    name  = "Tools"
    url   = "/page/tools/"
    weight = 20

  [[menu.main]]
    name  = "About"
    url   = "/page/about/"
    weight = 30

  [[menu.main]]
    name  = "Contact"
    url   = "/page/contact/"
    weight = 40

# Taxonomies
[taxonomies]
  tag      = "tags"
  category = "categories"

# Privacy
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true

# Markup
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4

