name: daily-content

on:
  schedule:
    # 09:15 AM US/Pacific ≈ 16:15 UTC
    - cron: "15 16 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: daily-content
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate posts (with retries)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          POSTS_PER_RUN: "2"
          MODEL_OUTLINE: "gpt-5-mini"
          MODEL_DRAFT: "gpt-5-mini"     # flip to "gpt-5" if you have access
          DISABLE_HEARTBEAT: "1"        # skip heartbeat files in CI
        run: |
          set -euo pipefail
          attempts=0
          until ./scripts/generate_posts.py; do
            code=$?
            attempts=$((attempts+1))
            if [ $attempts -ge 5 ]; then
              echo "generator failed after $attempts attempts (exit $code)"
              exit $code
            fi
            sleep $(( attempts * 10 ))   # 10s, 20s, 30s, ...
          done

      - name: Commit & push new posts
        id: commit
        run: |
          set -euo pipefail
          git config user.name  "Content Bot"
          git config user.email "bot@users.noreply.github.com"
          git add content/posts/*.md || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          git commit -m "chore: daily AI posts"
          git push
          echo "changed=1" >> "$GITHUB_OUTPUT"

      - name: Collect URLs to verify
        id: urls
        if: steps.commit.outputs.changed == '1'
        run: |
          set -euo pipefail
          # Files in the last commit
          git log -1 --name-only --pretty="" | grep '^content/posts/.*\.md$' || true > /tmp/changed_files.txt
          # Build full URLs for sitemap check
          BASE_URL="https://aibookkeepingtools.com"
          : > /tmp/urls.txt
          while read -r f; do
            [ -z "$f" ] && continue
            slug="$(basename "$f" .md)"
            echo "${BASE_URL}/posts/${slug}/" >> /tmp/urls.txt
          done < /tmp/changed_files.txt
          echo "URLs to verify:"
          cat /tmp/urls.txt || true
          # Expose a flag for next step
          if [ -s /tmp/urls.txt ]; then
            echo "have_urls=1" >> "$GITHUB_OUTPUT"
          else
            echo "have_urls=0" >> "$GITHUB_OUTPUT"
          fi

      - name: Wait for deploy & verify sitemap
        if: steps.urls.outputs.have_urls == '1'
        run: |
          set -euo pipefail
          BASE_URL="https://aibookkeepingtools.com"
          SITEMAP="${BASE_URL}/sitemap.xml"

          # Retry up to ~10 minutes (20 * 30s)
          tries=0
          max=20
          ok=0
          while [ $tries -lt $max ]; do
            echo "Fetching sitemap (attempt $((tries+1))/$max): $SITEMAP"
            map="$(curl -fsSL -A 'CI-Sitemap-Check' "$SITEMAP" || true)"
            if [ -z "$map" ]; then
              echo "Sitemap not reachable yet."
            else
              missing=0
              while read -r url; do
                [ -z "$url" ] && continue
                echo "  Checking: $url"
                echo "$map" | grep -F "$url" >/dev/null || missing=$((missing+1))
              done < /tmp/urls.txt

              if [ $missing -eq 0 ]; then
                echo "All new URLs found in sitemap ✅"
                ok=1
                break
              else
                echo "$missing URL(s) not yet in sitemap."
              fi
            fi
            tries=$((tries+1))
            sleep 30
          done

          if [ $ok -ne 1 ]; then
            echo "Sitemap did not include all new URLs within the wait window."
            echo "This can happen if the build is still in progress — check Cloudflare Pages."
            exit 1
          fi

