name: Repair & Rebuild (Cloudflare Pages)

on:
  workflow_dispatch: {}   # run manually from the Actions tab

permissions:
  contents: write         # needed to push fixes/bumps to main

concurrency:
  group: repair-rebuild
  cancel-in-progress: false

jobs:
  repair_rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git identity
        run: |
          git config user.name  "Content Bot"
          git config user.email "bot@users.noreply.github.com"

      - name: Sanity/repair: remove submodule & vendor PaperMod (idempotent)
        shell: bash
        run: |
          set -euo pipefail
          changed=0

          echo "==> Step 1: remove submodule traces (if any)"
          # Deinit + remove submodule working tree if present
          git submodule deinit -f themes/PaperMod 2>/dev/null || true
          git rm -f themes/PaperMod 2>/dev/null || true
          rm -rf .git/modules/themes/PaperMod || true

          # If .gitmodules exists and mentions PaperMod, drop that block/file
          if [ -f .gitmodules ]; then
            cp .gitmodules .gitmodules.bak || true
            sed -i '/^\[submodule "themes\/PaperMod"\]/,/^\s*$/d' .gitmodules
            if ! grep -q '[^[:space:]]' .gitmodules; then
              # file is empty -> remove it from Git
              if git ls-files --error-unmatch .gitmodules >/dev/null 2>&1; then
                git rm -f .gitmodules
                changed=1
              else
                rm -f .gitmodules
              fi
            else
              # still has content -> update tracked file
              git add .gitmodules
              changed=1
            fi
          fi

          # Scrub repo config keys if any remain
          git config --remove-section submodule.themes/PaperMod 2>/dev/null && changed=1 || true

          echo "==> Step 2: vendor PaperMod if missing"
          if [ ! -d themes/PaperMod ]; then
            # Use subtree to vendor theme at the requested prefix
            git subtree add --prefix themes/PaperMod https://github.com/adityatelange/hugo-PaperMod.git master --squash
            changed=1
          fi

          echo "==> Step 3: commit repairs if any"
          if ! git diff --quiet || ! git diff --cached --quiet || [ "$changed" -ne 0 ]; then
            git add -A
            git commit -m "ci: repair theme vendoring & submodule config (PaperMod)"
          else
            echo "No repair changes to commit."
          fi

      - name: Install Hugo (extended 0.147.0) for a quick build sanity check
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.0'
          extended: true

      - name: Build site (sanity)
        run: |
          hugo --gc --minify --cleanDestinationDir
          test -f public/index.html

      - name: Ensure a commit exists to trigger Pages (allow-empty if needed)
        run: |
          # If previous steps didn’t commit anything, make a no-op commit
          if git diff --quiet && git diff --cached --quiet; then
            git commit --allow-empty -m "chore(rebuild): force Cloudflare Pages deploy $(date -u +%FT%TZ)"
          fi

      - name: Push to main (triggers Cloudflare deploy)
        run: |
          git push origin HEAD:main

