name: Repair & Rebuild (Cloudflare Pages)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  repair_rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git identity
        shell: bash
        run: |
          git config user.name "Content Bot"
          git config user.email "bot@users.noreply.github.com"

      - name: Remove submodule traces (idempotent)
        shell: bash
        run: |
          set -euo pipefail
          git submodule deinit -f themes/PaperMod 2>/dev/null || true
          git rm -f themes/PaperMod 2>/dev/null || true
          rm -rf .git/modules/themes/PaperMod || true

          if [ -f .gitmodules ]; then
            sed -i '/^\[submodule "themes\/PaperMod"\]/,/^\s*$/d' .gitmodules
            # If file became empty, remove it from git; else re-add changes
            if [ ! -s .gitmodules ]; then
              git rm -f .gitmodules || rm -f .gitmodules
            else
              git add .gitmodules
            fi
          fi

          git config --remove-section submodule.themes/PaperMod 2>/dev/null || true

      - name: Vendor PaperMod via subtree (if missing)
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -d themes/PaperMod ]; then
            git subtree add --prefix themes/PaperMod https://github.com/adityatelange/hugo-PaperMod.git master --squash
          fi

      - name: Commit repairs if any
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --quiet || ! git diff --cached --quiet; then
            git add -A
            git commit -m "ci: repair theme vendoring & submodule config (PaperMod)"
          fi

      - name: Install Hugo (extended 0.147.0)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.0'
          extended: true

      - name: Build site (sanity)
        shell: bash
        run: |
          set -euo pipefail
          hugo --gc --minify --cleanDestinationDir
          test -f public/index.html

      - name: Ensure a commit exists to trigger Pages
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet && git diff --cached --quiet; then
            git commit --allow-empty -m "chore(rebuild): force Cloudflare Pages deploy $(date -u +%FT%TZ)"
          fi

      - name: Push to main (triggers Cloudflare deploy)
        shell: bash
        run: |
          set -euo pipefail
          git push origin HEAD:main

